// GENERATED by tools/blender/build_steen.py (issue #10, interiors are real): do not edit. Every real opening of the
// Steen's shell (client/public/models/steen.glb, whose empties opening_<id> are the same), in the WORLD's frame
// (world/landmarkHalls.ts moves them into the hall's: shellOpening.ts inFrame). x, z: its middle on the wall's outer
// face; (tx, tz) along it, (nx, nz) out of it; poly its outline where the reveal ends (u along from the middle,
// world y); depth the reveal's depth into the wall.

import type { ShellOpening } from "./shellOpening.js";

export const SHELL_OPENINGS: ShellOpening[] = [
  { id: "st_000", kind: "door", part: "steen", label: "the gatehouse, the museum's door", glaze: "", shape: "rect", x: -183.5, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 1.25, yb: 2.2, yt: 4.936, arch: false, depth: 0, poly: [[-1.25, 2.2], [1.25, 2.2], [1.25, 4.936], [-1.25, 4.936]] },
  { id: "st_001", kind: "window", part: "steen", label: "the gatehouse, the small window south of the door", glaze: "bars", shape: "rect", x: -185.6, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 0.35, yb: 3.6, yt: 4.8, arch: false, depth: 0.15, poly: [[0.35, 3.6], [0.35, 4.8], [-0.35, 4.8], [-0.35, 3.6]] },
  { id: "st_002", kind: "window", part: "steen", label: "the gatehouse, the small window north of the door", glaze: "bars", shape: "rect", x: -181.4, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 0.35, yb: 3.6, yt: 4.8, arch: false, depth: 0.15, poly: [[0.35, 3.6], [0.35, 4.8], [-0.35, 4.8], [-0.35, 3.6]] },
  { id: "st_003", kind: "window", part: "steen", label: "the prison range, the hall of antiquities, window 1 on the courtyard", glaze: "bars", shape: "rect", x: -178.9, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 0.7, yb: 3.4, yt: 6.1, arch: false, depth: 0.15, poly: [[0.7, 3.4], [0.7, 6.1], [-0.7, 6.1], [-0.7, 3.4]] },
  { id: "st_004", kind: "window", part: "steen", label: "the prison range, the hall of antiquities, window 2 on the courtyard", glaze: "bars", shape: "rect", x: -175.7, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 0.7, yb: 3.4, yt: 6.1, arch: false, depth: 0.15, poly: [[0.7, 3.4], [0.7, 6.1], [-0.7, 6.1], [-0.7, 3.4]] },
  { id: "st_005", kind: "window", part: "steen", label: "the prison range, the hall of antiquities, window 3 on the courtyard", glaze: "bars", shape: "rect", x: -172.5, z: -23.25, tx: 1, tz: 0, nx: 0, nz: 1, hw: 0.7, yb: 3.4, yt: 6.1, arch: false, depth: 0.15, poly: [[0.7, 3.4], [0.7, 6.1], [-0.7, 6.1], [-0.7, 3.4]] },
];
