// Pure browser prison geometry and checked NPC rounds; no scene bake or saved game.
import {writeFileSync} from "node:fs";
import * as P from "../../shared/prisonPlan.ts";
import {freeAt} from "../../shared/hallPlan.ts";
import {groundRound} from "../../shared/localRound.ts";
const m=P.PLAN.marks, specs=[];
const add=(id,kind,mark,motion,on,seat=.45,pacing=null,gov=false)=>specs.push({id,kind,x:mark.x,z:mark.z,y:mark.y??0,yaw:mark.yaw,motion,on,seat,pacing,gov});
add('guard','police',m.guardTable,'sit','guard');add('chief','police',m.chief,'behind','chief');add('visits','police',m.gangway,'sit','visits',.5);
add('corridorA','police',{x:16.5,z:19.5,yaw:-Math.PI/2},'idle','day');add('gate','police',{...P.GATE_WARDER,yaw:Math.PI},'behind','gate');
add('yard','police',{x:P.PARTS.ring.x,z:P.PARTS.ring.z,yaw:0},'behind','yard');
add('cellA','docker_c',{x:18,z:16.1,yaw:Math.PI/2},'sit','always',.55,P.cellPacing('A','S',4));
add('cellB','old_man',{x:-15.2,z:22.4,yaw:-Math.PI/2},'sit','always',.55,P.cellPacing('B','N',3));
add('corridorB','police',m.corridorB,'idle','day');add('galleryB','police',m.galleryB,'idle','day');
add('clerk','old_man',m.clerk,'sit','clerk');add('director','old_man',m.director,'sit','director');
add('governor','old_man',{x:-24,z:6.9,yaw:Math.PI},'sit','governor',.45,null,true);add('visitor','docker_a',m.prisoner,'idle','visitor');
const output=specs.map((s,i)=>{const stand=(x,z)=>s.pacing?s.pacing(x,z):s.id==='gate'?z<-.65:s.id==='yard'?Math.hypot(x-P.PARTS.ring.x,z-P.PARTS.ring.z)<P.PARTS.ring.r_in-1:freeAt(s.gov?P.GOV_PLAN:P.PLAN,x,z,.25,false,()=>true,s.y);
 const {round}=groundRound({standFree:stand},[s.x,s.z],s.y,s.yaw,s.motion==='sit',i*7,s.kind==='police'?2:1.2);
 return {...s,pacing:undefined,gov:undefined,seed:i*7,home:round.home,routes:round.routes};});
const rows=[];for(let z=-3;z<=31;z+=.3){let row='';for(let x=-33;x<=31;x+=.3)row+=freeAt(P.PLAN,x,z,.3,false,()=>true,0)?'1':'0';rows.push(row);}
const plan={...P.PLAN,freeGrid:{x:-33,z:-3,step:.3,rows}};
const json=JSON.stringify({origin:P.ORIGIN,yaw:P.YAW,ring:P.PARTS.ring,plan,specs:output});
writeFileSync(new URL('../../godot/src/People/PrisonData.cs',import.meta.url),`// Generated by tools/godot/prison-data.mjs from the browser's prison and local rounds.
namespace Scheldemist.People;
public static class PrisonData {public const string Json = """
${json}
""";}
`);
console.log(`${output.length} checked prison rounds; ${rows.length} floor-grid rows.`);
